import type { Metadata } from "next";
import "../shared/styles/globals.css";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import theme from "../lib/mantine/theme";
import Footer from "@/pages/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-canvas min-h-full flex flex-col">
        <MantineProvider theme={theme}>
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
